### ISSUE TITLE
Peer to Peer Code Review

### ISSUE THREAD

**Issue by mandelatuks** [bamsi/jukwaa#10]
# kindly check the following issue:

- In the read me file it will be good to include the screenshot of your so that it looks more professional 
- Adjust the show more button-text  in the mobile version from 'MORE'  to 'LESS' when the user clicks it

The codes look clean and neat 🥇, I learned something from your project.

**Comment by bamsi** [comment]
Thank you the team! I have fixed all the issues.
Happy coding! 🥇
